version: '3.8'

services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      MONGO_URI: "mongodb+srv://victorbarny4:Yungvicky007@cluster0.62hifgz.mongodb.net/"
      redisURL: "redis://red-co18cita73kc73f4ck40:6379"
    depends_on:
      - redis

  mongo:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"

  redis:
    image: redis
    ports:
      - "6379:6379"
